version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kitchen_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: kitchen_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kitchen
      MYSQL_USER: kitchen_user
      MYSQL_PASSWORD: secret_password
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: kitchen_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app

  duckdns:
    image: linuxserver/duckdns:latest
    container_name: kitchen_duckdns
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      SUBDOMAINS: homekitchen
      TOKEN: f13efdef-7cbc-4993-b8e5-457af8efbde9
    volumes:
      - ./duckdns:/config

volumes:
  db_data:
